services:
  coredns-comarca:
    image: coredns/coredns:latest
    container_name: coredns
    command: -conf /etc/coredns/Corefile -dns.port 53
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - "5353:53"
      - "5353:53/udp"
      - "8080:8080"
    volumes:
      - ./conf/Corefile:/etc/coredns/Corefile
      - ./conf/db.tierramedia.jc:/etc/coredns/db.tierramedia.jc
    networks:
      tierramedia:
        ipv4_address: 192.168.103.253
    domainname: tierramedia.jc
    hostname: comarca

  client-lothlorien:
    image: ubuntu:latest
    container_name: lothlorien
    command: bash -c "
      echo 'tzdata tzdata/Areas select Europe' | debconf-set-selections &&
      echo 'tzdata tzdata/Zones/Europe select Madrid' | debconf-set-selections &&
      apt update &&
      DEBIAN_FRONTEND=noninteractive apt install -y tzdata &&
      dpkg-reconfigure --frontend noninteractive tzdata &&
      apt upgrade -y &&
      apt install -y
        iputils-ping
        dnsutils
        net-tools &&
      sleep infinity"
    stdin_open: true
    tty: true
    #entrypoint: /bin/bash
    depends_on:
      - coredns-comarca
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    networks:
      tierramedia:
        ipv4_address: 192.168.103.16 
    dns:
      - 192.168.103.253
    domainname: tierramedia.jc
    hostname: lothlorien
      
networks:
  default:
    driver: bridge 
  tierramedia:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.103.0/24  